import './globals.css';

// flat icons
import '@/icons/flat-icons/uicons-bold-rounded/css/uicons-bold-rounded.css'
import '@/icons/flat-icons/uicons-regular-rounded/css/uicons-regular-rounded.css'
import '@/icons/flat-icons/uicons-solid-rounded/css/uicons-solid-rounded.css'
import '@/icons/flat-icons/uicons-solid-straight/css/uicons-solid-straight.css'
import '@/icons/flat-icons/uicons-bold-straight/css/uicons-bold-straight.css'
import '@/icons/flat-icons/uicons-regular-straight/css/uicons-regular-straight.css' 
// end flat icons

// fontawesome
import '@/icons/fontawesome/css/all.min.css'
// end fontawesome

import { Inter } from 'next/font/google';
import  StoreProvider  from '@/redux/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
